#!/bin/sh

export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus 
export XMODIFIERS="@im=fcitx"

export GDK_BACKEND=wayland
export QT_QPA_PLATFORM=wayland-egl
export XDG_SESSION_TYPE=wayland
export QT_WAYLAND_FORCE_DPI=physical
export SDL_VIDEODRIVER=wayland
export MOZ_ENABLE_WAYLAND=1
export LIBSEAT_BACKEND=logind

exec sway $@
